### ISSUE TITLE
Redirect URI is not correct in ReadMe

### ISSUE THREAD

**Issue by fmorenoper** [juan518munoz/ZeppOS-Spotify#13]
URI: https://juan518munoz.github.io/ZeppOS-Spotify-Web should be added to the Redirect URIs section in the spotify app configuration

<img width="963" alt="Screen Shot 2023-08-21 at 17 06 11" src="https://github.com/juan518munoz/ZeppOS-Spotify/assets/4210791/3123dde6-821a-4b47-ba57-b78fe3794f20">

**Comment by juan518munoz** [comment]
Modified, thanks for the heads up!
