### ISSUE TITLE
Does it work with API 1.0?

### ISSUE THREAD

**Issue by ThinkAndFly** [juan518munoz/ZeppOS-Spotify#14]
Juan, la pregunta es esa, funciona con ZeppOS  1? es un GTR2 .

La verdad que excelente trabajo con la app.

**Comment by juan518munoz** [comment]
Sí, esta hecha para funcionar con ZeppOS 1.0, sin embargo el Amazfit GTR 2 no posee ZeppOS.

https://docs.zepp.com/docs/1.0/reference/related-resources/device-list/

**Comment by ThinkAndFly** [comment]
ahh  entonces lo voy a cambiar por el 4, pq lo compré porque soporta
llamadas pero es muy limitado, es casi una band.

gracias por la información!
