### ISSUE TITLE
Beta testing

### ISSUE THREAD

**Issue by juan518munoz** [juan518munoz/ZeppOS-Spotify#2]
I think the development has reached a fairly stable point, not needing to do hacky things to get the necessary tokens for the player to work, it still is far away from being finish. Those interested in trying out the app leave a comment down bellow, requirements are:

1. Must have a Spotify Premium account.

2. Must be willing to share their associated email (via private message of course) to get access to the dev API.

3. Your device has to be the Amazfit Band 7.

**Comment by Areg472** [comment]
Can I join to try it pls?

**Comment by juan518munoz** [comment]
Yes, please email me at juanmunoz890@gmail.com, subject: Spotify for ZeppOS, add your associated spotify email in the body of the mail, remember it needs to be a premium account.
