### ISSUE TITLE
Request your work to be included in the awesome Zepp OS project

### ISSUE THREAD

**Issue by MyoungXUE** [juan518munoz/ZeppOS-Spotify#3]
Hello @juan518munoz 

Please allow me to introduce myself, I am Myoung XUE, an engineer from Zepp OS Team.

We have an awesome project https://github.com/zepp-health/awesome-zeppos, as the name suggests, where we include many projects from the community that are relevant to Zepp OS.

We noticed that several of your projects are publicly available on Github and would like to ask your permission to include them in the official awesome zeppos repository.

Hopefully, we can get your approval and your project will help more developers in the community.

**Comment by juan518munoz** [comment]
Greetings @MyoungXUE 

Of course you have permission to include this and any other future proyect I make available on github on awesome-zeppos as well as any website you deem appropiate.

Sharing is learning, learning will make the community bigger.
